version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    command: postgres -c "max-connections=10"
    expose:
      - '5432'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB_MAIN=main
      - POSTGRES_ROOT_PASSWORD=main
    volumes:
      - .docker-cache/pg:/var/lib/postgresql/data:delegated
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U main -d main']
      interval: 5s